### ISSUE TITLE
install problem 

### ISSUE THREAD

**Issue by Bea-Taylor** [ucl-pond/kde_ebm#8]
error installing kde_ebm using command 'pip install requirements.txt': 

ERROR: Command errored out with exit status 1: /share/apps/python-3.7.2-shared/bin/python3.7 /share/apps/python-3.7.2-shared/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-2rgf3jtt/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'numpy>=1.6.1' pybind11 'scipy>=0.9' 'matplotlib>=2.0.1' wheel Check the logs for full command output.

solved by removing the file pyproject.toml

**Comment by sea-shunned** [comment]
Just to add to this, as I've seen this issue come up twice now, with both issues resolved by removing `pyproject.toml`.

The first scenario was with a M1 Mac, where there were compilation issues which were being forced due to the presence of `pyproject.toml`, which changes how things are built.

The second was on the HPC, where `AttributeError: module 'enum' has no attribute 'IntFlag'` was the error. [The usual way to solve this](https://stackoverflow.com/questions/58890684/attributeerror-module-enum-has-no-attribute-intflag-fastai-install) is not possible in that scenario, but removing `pyproject.toml` fixed it (presumably by avoiding wheels but I haven't looked into it).

The issue (requiring `numpy` installed before installing!) that was solved by adding `pyproject.toml` did not arise in the two cases above, but probably would with a fresh environment. Either way, we need to dig a little and get it working universally.

**Comment by noxtoby** [comment]
I think `numpy` was only required for the old installation via `[setup.py](https://github.com/ucl-pond/kde_ebm/blob/master/setup.py)`. Should be safe to remove
